language: ruby
  rvm:
  - 2.4.0
  script:
  - yarn install
  app:
      master: website-planning
      prod: website-planning
    on:
      repo: dben89x/website-planning
    skip_cleanup: true
  notifications:
    email: false
